apiVersion: v1
kind: Service
metadata:
  name: {{ include "my_rest_api.name" . }}
  labels:
    app: {{ include "my_rest_api.name" . }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: {{ include "my_rest_api.name" . }}
